# Generated by Django 4.2 on 2023-05-02 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='artist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apis.artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='works',
            field=models.ManyToManyField(related_name='artists', to='apis.work'),
        ),
    ]
